#!/bin/bash

# Script to install wordpress on ubuntu server

# Ask for user to establish a database username and password for configuration

read -p 'wordpress_db_name [wp_db]:' wordpress_db_name
read -p 'wordpress_db_username:' wp_username 
read -p 'db_root_password [only-alphanumeric]:' db_root_password
echo



# Install AWS extra packages for Linux 2

echo "Installing AWS extra packages for Linux 2..."
echo -e $(sudo amazon-linux-extras install -y)
echo -e $(sudo amazon-linux-extras install php7.2 -y)
echo -e $(sudo yum install lamp-mariadb10.2-php7.2 -y)
echo "Successfully installed AWS extra packages"

# Update and install apache2
echo "Installing apache" 
echo -e $(sudo yum install httpd -y) 
echo -e $(sudo systemctl stop httpd) 
echo -e $(sudo systemctl start httpd) 
echo -e $(sudo systemctl enable httpd)
echo "Apache installed successfully..."

# Update and install mysql
echo "Installing mysql" 
echo -e $(sudo yum install mariadb-server -y) 
echo -e $(sudo systemctl start mariadb)
echo -e $(sudo systemctl enable mariadb)
echo -e $(sudo systemctl restart mariadb)
echo "MySQL installed successfully..."


#Install PHP Addons

echo -e $(sudo yum install php-cgi -y)
echo "Installed php-cgi successfully..."
echo -e $(sudo yum install php-cli -y)
echo "Installed php-cli successfully..."
echo -e $(sudo yum install php-gd -y)
echo "Installed php-gd successfully..."
echo -e $(sudo yum install imagemagick -y)
echo "Installed imagemagick successfully..." 
echo -e $(sudo apt-get install php-imagick -y)
echo "Installed imagick successfully..." 
echo -e $(sudo yum install php-bcmath -y)
echo "Installed php-bcmath successfully..." 
echo -e $(sudo yum install php-curl -y)
echo "Installed php-curl..."
echo -e $(sudo yum install php-intl -y)
echo "Installed php-intl..."
echo -e $(sudo yum install php-json -y)
echo "Installed php-json..."
echo -e $(sudo yum install php-mbstring -y)
echo "Installed php-mbstring..."
echo -e $(sudo yum install php-xml -y)
echo "Installed php-xml..."
echo -e $(sudo yum install php-zip -y)
echo "Installed php-zip..."

echo "PHP extensions successfully installed" 

#Install Wordpress and create installation directory
echo "Installing Wordpress and creating installation directory"
echo -e $(wget https://wordpress.org/latest.zip)
echo -e $(sudo yum install unzip -y)
echo -e $(unzip latest.zip)
echo -e $(sudo cp -r /home/ec2-user/wordpress/* /var/www/html/)
echo -e $(sudo chown -R apache /var/www)
echo -e $(sudo chgrp -R apache /var/www)
echo -e $(sudo chmod -R 2755 /var/www)
echo -e $(sudo find /var/www -type d -exec sudo chmod 2775 {} \;)
echo -e $(sudo systemctl restart httpd)
echo "Successfully installed Wordpress..." 



# Configure mysql database for wordpress
echo "Configuring MySQL Database" 
sudo mysql -u root -e "CREATE DATABASE $wordpress_db_name;"
sudo mysql -u root -e "CREATE USER '$wp_username'@'%' IDENTIFIED BY '$db_root_password';"
sudo mysql -u root -e "GRANT ALL PRIVILEGES on *.* to '$wp_username'@'%';"
sudo mysql -u root -e "FLUSH PRIVILEGES;"

echo "Database configured"

## fix .htaccess file so that permalinks work correctly
echo "Fixing Wordpress permalinks..."
echo -e $(touch /home/ec2-user/.htaccess)
echo -e $(sudo rm /var/www/html/.htaccess)
echo "
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>" > /home/ec2-user/.htaccess
echo -e $(sudo cp /home/ec2-user/.htaccess /var/www/html/)
echo -e $(sudo rm /home/ec2-user/.htaccess)
echo -e $(sudo cp /home/ec2-user/httpd.conf /etc/httpd/conf/httpd.conf)
echo "Fixed permalinks!"
echo -e $(sudo systemctl restart httpd)


 
echo "Success!!" 


#For future development, I want to add a script to install the SSL 
# certificate for the site. 
# Also, would like to have a feature that automatically creates a database password possibly?



